# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# compile CXX with /home/kinuxroot/Applications/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++
CXX_FLAGS = -fpic -Wno-psabi --sysroot=/home/kinuxroot/Applications/android-ndk-r13b/platforms/android-9/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack  -fopenmp -fno-rtti -fno-exceptions -mthumb -fomit-frame-pointer -fno-strict-aliasing -O3 -DNDEBUG -isystem /home/kinuxroot/Applications/android-ndk-r13b/platforms/android-9/arch-arm/usr/include -isystem /home/kinuxroot/Applications/android-ndk-r13b/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /home/kinuxroot/Applications/android-ndk-r13b/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem /home/kinuxroot/Applications/android-ndk-r13b/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -I/home/kinuxroot/Projects/other/cpp/ncnn/src -I/home/kinuxroot/Projects/other/cpp/ncnn/build-android-armv7/src -I/home/kinuxroot/Projects/other/cpp/ncnn/src/layer    -Wall -Wextra -fPIC -Ofast -ffast-math -fvisibility=hidden -fvisibility-inlines-hidden

CXX_DEFINES = -DANDROID

